import discord
from datetime import datetime
from secret import * # imports image links 
from secret import footer_text

# Class that generated default embeds for the purposes of nicely formatting embeds generated by cog commands

class EmbedWrapper():
    def __init__(self):
        self.embed = discord.Embed(
            title='',
            description='',
            url='',
            color=discord.Color.random(),
            timestamp=datetime.now()
        )

    async def return_base_embed(self): 
        return self.embed
    
    async def return_embed(self, image, command_type, message):
        self.embed.set_thumbnail(url=image)
        self.embed.add_field(name=f"Command Output {command_type}", value=f"\n\n ```{message}```")
        return self.embed
    
