import discord
from datetime import datetime
from secret import * # imports image links 
from secret import footer_text

# Class that generated default embeds for the purposes of nicely formatting embeds generated by cog commands

class EmbedWrapper():
    def __init__(self):

        embed = discord.Embed(
            title='',
            description='',
            url='',
            color=discord.Color.random(),
            timestamp=datetime.now()
        )   

        self.embed = embed

    def return_base_embed(self): 
        return self.embed

